// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRadios() {
  return window['go']['main']['App']['GetRadios']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
